spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/student_db
    username: sms_user
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-disabled: false

eureka:
  client:
    enabled: true

logging:
  level:
    com.sms.student: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  upload:
    dir: uploads/students
