spring:
  datasource:
    url: jdbc:postgresql://postgres-student:5432/student_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true

eureka:
  instance:
    hostname: student-service
    prefer-ip-address: false
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://eureka-server:8761/eureka/}

logging:
  level:
    com.sms.student: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

app:
  upload:
    dir: ${UPLOAD_DIR:/app/uploads/students}
